# Site settings
title: Hakan ERGÜL - İnternet Günlüğüm 
email: hknrgl [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hakanergul.github.io"
# the base hostname & protocol for your site
facebook: "https://www.facebook.com/hakan.ergul.900"
google_plus: "https://plus.google.com/u/0/109572384957839463729"
disqus_shortname: H. ERGUL
github_username:  hakanergul

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--more-->
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude: ["README.md"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
