# Site Info
title:              "Hakan ERGÜL"
description:        "Matematik ağırlıklı yazılarımdam oluşan internet günlüğüm"
#google_verify:       # Put your Google Verification here
#google_analytics:    # Put your Google Analytics code

# Author Info
author_name:        "Hakan ERGÜL"
author_email:       hknrgl@gmail.com

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /:title # Post permalink
timezone:           Asia/Istanbul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
